---
output:
  word_document:
    reference_docx: ../templates/template_tables_portrait.docx
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(here)
library(pander)
library(kableExtra)
library(knitr)
library(dplyr)
library(flextable)
library(officer)
library(here)
library(openxlsx)
# library(ReporteRs)
```

```{r}
d <- read.xlsx(here::here("data", "Table_1.xlsx"), "t1")

d1 <- d %>% 
  separate("Revista", c("Revista", "Revista_href"), sep = "]") %>%
  separate("URLs.útiles.(criterios.de.repositorio)", c("CriterioRepo", "CriterioRepo_href"), sep = "]") %>% 
  separate("URLs.útiles.(política.de.datos)", c("pd", "pd_href"), sep = "]") %>% 
  mutate(Revista = str_sub(Revista, 2)) %>% 
  mutate(CriterioRepo = str_sub(CriterioRepo, 2)) %>% 
  mutate(pd = str_sub(pd, 2)) %>% 
  mutate(Revista_href = str_sub(Revista_href, 2, -2)) %>% 
  mutate(CriterioRepo_href = str_sub(CriterioRepo_href, 2, -2)) %>% 
  mutate(pd_href = str_sub(pd_href, 2, -2))  



t1 <- flextable(d1, col_keys = c("Ranking","Revista","Factor.de.Impacto.2017.(JCR,.Clarivate.Analytics,.2018)",                          "Tipo.de.artículo.principal","Obligatoriedad.de.la.política.de.datos",
                                 "CriterioRepo", "pd"))
tabla1 <- compose(t1, j = "Revista", value = as_paragraph(hyperlink_text(x= Revista, url = Revista_href))) 

tabla1 <- compose(tabla1, j = "CriterioRepo", value = as_paragraph(hyperlink_text(x="CriterioRepo", url = "CriterioRepo_href"))) 


  compose(j = "pd", value = as_paragraph(hyperlink_text(x="pd", url = "pd_href"))) 



tabla1 <- flextable(tabla1, col_keys = c("Ranking","Revista"))





t1 <- t1 %>% set_header_labels(values = list(
  "Factor.de.Impacto.2017..JCR..Clarivate.Analytics..2018." = "Factor de Impacto ^1",
  "Tipo.de.artículo.principal" = "Tipo de Artículo Principal",
  "Obligatoriedad.de.la.política.de.datos" = "Obligatoriedad de la política de datos",
  "URLs.útiles..criterios.de.repositorio." = "URL's útiles. Criterios de repositorio",
  "URLs.útiles..política.de.datos." = "URL's útiles. Política de datos"
  ))

t1 

t1 <- flextable(d1)
ft <- display(t1, col_key = "Revista", 
              pattern = "# {{mylink}}",
              formatters = list(mylink ~ hyperlink_text(Revista_href, Revista)))

              
              
ft <- display(
    t1, col_key = "col", pattern = "# {{mylink}}",
    formatters = list(mylink ~ hyperlink_text(href, col) )
)
ft 




              

ft <- flextable(head( mtcars, n = 10))
ft <- display(ft, col_key = "carb",
  i = ~ drat > 3.5, pattern = "# {{carb}}",
  formatters = list(carb ~ sprintf("%.1f", carb)),
  fprops = list(carb = fp_text(color="orange") ) )
ft <- autofit(ft)





ft <- display(
    ft, col_key = "col", pattern = "# {{mylink}}",
    formatters = list(mylink ~ hyperlink_text(href, col))
)
ft 


  

t1 <- flextable(d1)
tabla1 <- t1 %>% 
  compose(j = "Revista", value = as_paragraph(hyperlink_text(x="Revista", url = "Revista_href"))) 



%>% 


tabla1


tabla <- display(tabla1, col_key = c("Ranking", "Revista", "Factor.de.Impacto.2017..JCR..Clarivate.Analytics..2018.",
                         "Obligatoriedad.de.la.política.de.datos", "CriterioRepo", "pd"))

%>% 
  display(col_keys = c("Ranking", "Revista", "Factor.de.Impacto.2017..JCR..Clarivate.Analytics..2018.",
                         "Obligatoriedad.de.la.política.de.datos", "CriterioRepo", "pd"))
  
              
  set_header_labels(values = list(
  "Factor.de.Impacto.2017..JCR..Clarivate.Analytics..2018." = "Factor de Impacto ^1",
  "Tipo.de.artículo.principal" = "Tipo de Artículo Principal",
  "Obligatoriedad.de.la.política.de.datos" = "Obligatoriedad de la política de datos",
  "URLs.útiles..criterios.de.repositorio." = "URL's útiles. Criterios de repositorio",
  "URLs.útiles..política.de.datos." = "URL's útiles. Política de datos"
  )) %>% 






tabla1

  
```




